name: Deploy app

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
  cmd:
    runs-on: ubuntu-latest
    steps:
    - name: SSH exec
      uses: JimCronqvist/action-ssh@v0.1.1
      with:
        hosts: '${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        command: |
          cd /home/deploy; yarn; yarn ts-node src/app.ts https://bsc-dataseed2.binance.org 0x67464d0947CfCA965A1ac2dded97b8C3c9921865 0x1Ee38d535d541c55C9dae27B12edf090C608E6Fb 1000
