name: Deploy app

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install rsync
      run: sudo apt install rsync
    - name: Create ssh folder
      run: mkdir /home/runner/.ssh
    - name: Writing private key
      run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > /home/runner/.ssh/deploy_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set permissions
      run: 'chown -R runner: /home/runner/.ssh/; chmod 755 /home/runner/.ssh; chmod 0600 /home/runner/.ssh/deploy_key'
    - name: Check ssh permissions
      run: 'ssh -i /home/runner/.ssh/deploy_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "w"'
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
