name: Deploy app

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install rsync
      run: sudo apt install rsync
    - name: check folder
      run: sudo ls -la /home/runner/
    
