name: Deploy app

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rsync
      run: sudo apt install -y rsync git
    - name: Create ssh folder
      run: mkdir /home/runner/.ssh
    - name: Writing private key
      run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > /home/runner/.ssh/deploy_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set permissions
      run: 'chown -R runner: /home/runner/.ssh/; chmod 755 /home/runner/.ssh; chmod 0600 /home/runner/.ssh/deploy_key'
    - name: Transfering files by rsync
      run: 'rsync /home/runner/work/liquidation-bot/liquidation-bot/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }} --rsh "ssh -p 22 -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no" --recursive -rltgoDzvO --delete'
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
    - name: Build deps
      run: 'ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd /home/deploy/project/ && yarn"'
