name: Deploy app

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install rsync
      run: sudo apt install rsync
    - name: Create ssh folder
      run: mkdir /home/runner/.ssh
    - name: Check user
      run: whoami
    - name: Writing private key
      run: echo ${{ secrets.PRIVATE_KEY }} > /home/runner/.ssh/deploy_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Check key
      run: cat /home/runner/.ssh/deploy_key
